# Generated by Django 3.0.2 on 2020-07-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid_boolean', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('favourite', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('LNK', 'Ссылка'), ('NT', 'Заметка'), ('MEM', 'Памятка'), ('TD', 'TO DO'), ('ETC', 'Другое')], default='NT', max_length=3)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
